[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "3gfWKGBgW5wq1PUQdNV2qipxcks1HNEAJjYgKCQKBJdy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/yanhong/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
